cask_args appdir: '/Applications'

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts"
tap "heroku/brew"

# System
brew "coreutils"
brew "git" # Always useful to have up-to-date versions
brew "openssh" # More up-to-date version than system

# Shell
brew "bat" # syntax highlighting cat
brew "diff-so-fancy" # Fancy diffs for git
brew "exa" # better ls
brew "fasd" # Autcompletion for directory jumping, z and v (for editing)
brew "fish" # shell
brew "fzf" # fuzzy finder in shell, <C-t> to bring up completion
brew "htop" # fancy top
brew "jq" # streaming, inline JSON editor
brew "shellcheck" # bash linter
brew "tmux" # terminal multiplexer, run multiple shells and save/restore sessions
brew "httpie" # simplified http client
cask "kitty" # Terminal emulator

# Shell Search
brew "grep" # the old standby
brew "fd" # fast find command
brew "the_silver_searcher" # ag for searching, fancy grep
brew "ripgrep" # rg for searching, fancy and fast grep

# Editor
brew "neovim" # Text editor
brew "vim" # Backup text editor
brew "watchman" # Needed by CoC.nvim
cask "visual-studio-code" # Code IDE

# Fonts
cask "font-fira-code" # Terminal Font
cask "font-firacode-nerd-font" # Install for VS Code & Kitty symbol_map
cask "font-hasklig" # Alternate (italic) terminal font
cask "font-tex-gyre-heros" # Used for CV on website

# Programming
brew "heroku/brew/heroku" # Build and install cloud apps
brew "node" # Node.js
brew "node-build" # Build Node binaries
brew "nodenv" # Manage different Node.js installations
brew "python" # Python 3
brew "rbenv" # Manage different Ruby installations
brew "yarn" # Package manager for Node.js
cask "virtualbox" # Virtual machine software

# Writing
brew "bib-tool" # Manage bibtex files
brew "diction" # Analyze a document's word usage
brew "pandoc" # Compile Markdown into .docx (and beyond!)
brew "pandoc-citeproc" # Citation plugin for Pandoc
brew "vale" # Markdown linter
cask "zotero" # Bibliography management
cask "basictex"

# Online Teaching
cask "licecap" # Animated GIF maker
cask "obs" # Screencap
cask "vlc" # Video playback
cask "avidemux" # Simple editing

# Other GUI Applications
cask "firefox" # Browser
cask "flux" # Night-time screen mode
cask "karabiner-elements" # Keyboard remapping
cask "keycast" # Visualize keystrokes on-screen, great for teaching
cask "seafile-client" # File sharing
# vim: filetype=conf
