#!/usr/bin/env bash
## Key Bindings

# Set compose key (for unicode) to menu:
setxkbmap -option compose:menu
# Always turn on numlock:
setxkbmap -option numpad:mac us
# Convert capslock to escape:
setxkbmap -option caps:escape

# reassign Alt_R to Super_L
xmodmap -e "keycode 108 = Super_L"
# make sure X keeps it out of the mod1 group
xmodmap -e "remove mod1 = Super_L"

export QT_QPA_PLATFORMTHEME=qt5ct
export DESKTOP_SESSION="xfce"
DOTFILES_TARGET="$( [ -e ~/.local/share/dotfiles/target ] && /bin/cat ~/.local/share/dotfiles/target)"
export DOTFILES_TARGET
xrdb ~/.Xresources
# vim:ft=sh
