dotfiles_dir = "dotfiles"

[[profiles.macos.hook]]
command = "env SERVER=true bash ~/dotfiles/bootstrap/init.sh"

[[profiles.linux.hook]]
command = "env SERVER=true bash ~/dotfiles/bootstrap/init.sh"

[[import]]
path = "~/dotfiles/bombadil/common.toml"

[[import]]
path = "~/dotfiles/bombadil/server-only.toml"
