dotfiles_dir = "dotfiles"

[[profiles.macos.hook]]
command = "bash ~/dotfiles/bootstrap/init.sh"

[[profiles.linux.hook]]
command = "bash ~/dotfiles/bootstrap/init.sh"

[[import]]
path = "~/dotfiles/bombadil/common.toml"

[[import]]
path = "~/dotfiles/bombadil/desktop-only.toml"
