[admiral]
items = ["left", "workspaces",
         "center", "title",
         "right", "network", "padding", "clock"]

[battery]
path = "bash ~/dotfiles/admiral.d/scripts/battery.sh"

[padding]
path = "echo -n '  '"

[network]
path = "bash ~/dotfiles/admiral.d/scripts/network_name.sh"

[workspaces]
path = "bash ~/dotfiles/admiral.d/scripts/workspace.sh"

[title]
path = "xtitle -s -t 50"

[clock]
path = "date '+%-I:%M%p  '"
reload = 1

# Used for formatting lemonbar
[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true
