-- Default mappings for select-digraphs
vim.keymap.set("i", "<C-k><C-k>", function()
	require("select-digraphs").select_digraph("i")
end)
vim.keymap.set("n", "r<C-k><C-k>", function()
	require("select-digraphs").select_digraph("r")
end)
vim.keymap.set("v", "r<C-k><C-k>", function()
	require("select-digraphs").select_digraph("gvr")
end)
