#!/usr/bin/env bash
source ~/dotfiles/conf/xorg/xinit-common
source ~/dotfiles/conf/xorg/xprofile-common

# Kill anything for XFCE4
pkill -f xfce4
pkill -f xfsettings
pkill -f xfconfd

DOTFILES_TARGET="$( [ -e ~/.local/share/dotfiles/target ] && /bin/cat ~/.local/share/dotfiles/target)"
if [ "$DOTFILES_TARGET" == "laptop" ]; then
	hsetroot -cover ~/dotfiles/backgrounds/wallhaven-nml81k.jpg
fi

# vim:ft=sh
