#!/usr/bin/env bash
source ~/dotfiles/conf/xorg/xinit-common

if [ "$DOTFILES_TARGET" != "laptop" ]; then
	pkill -f liskin-media
	liskin-media mpris-daemon &
fi

export DESKTOP_SESSION="awesome"
exec awesome >> ~/.cache/awesome/stdout 2>> ~/.cache/awesome/stderr
# vim:ft=sh
