#!/usr/bin/env bash
source ~/dotfiles/conf/xorg/xinit-common
source ~/dotfiles/conf/xorg/xprofile-common

DOTFILES_TARGET="$( [ -e ~/.local/share/dotfiles/target ] && /bin/cat ~/.local/share/dotfiles/target)"
if [ "$DOTFILES_TARGET" == "laptop" ]; then
	hsetroot -cover ~/dotfiles/backgrounds/wallhaven-nml81k.jpg
	cmst -m &
fi

# vim:ft=sh
