let &runtimepath .= ','.expand('~/dotfiles/vim/')
let &runtimepath .= ','.expand('~/dotfiles/vim/after/')
call plug#begin('~/.vim/plugged/desktop/')
runtime bundle/common.vim
runtime bundle/desktop.vim
call plug#end()
runtime common.vim
let configs = [
  \ 'deoplete',
  \ 'ale',
  \ 'autocomplete',
  \ 'folds',
  \ 'fuzzy',
  \ 'git',
  \ 'nvim-only',
  \ 'statusline',
  \ 'syntax',
  \ 'theme',
  \ 'todo',
  \ 'writing',
\]
for file in configs
  let x = 'config/'.file.'.vim'
  execute 'runtime' x
endfor
" Disable polyglot for all the syntaxes we already use:
let g:polyglot_disabled = dotfiles#polyglot#overrides()
" # vim:foldmethod=marker
