#! /bin/sh
# '#232323','#d2813d','#8c9e3d','#b1942b','#6e9cb0','#b58d88','#6da280','#949d9f','#312e30','#d0913d','#96a42d','#a8a030','#8e9cc0','#d58888','#7aa880','#aeadaf' 

pgrep -x sxhkd > /dev/null || sxhkd &
killall lemonbar
# admiral | lemonbar -g x30 -f 'Font Awesome 5 Free:size=13' -f 'Font Awesome 5 Brands:size=13' -f 'Font Awesome 5 Free Solid:size=13' -f 'Fira Code:size=14' -B '#232323' -F '#AEADAF' -a 32 |sh &
~/dotfiles/bspwm/scripts/xcolors &
~/dotfiles/bspwm/scripts/panel &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config normal_border_color  "#232323"
bspc config active_border_color  "#949d9f"
bspc config focused_border_color "#6e9cb0"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
