#!/bin/bash

# Source: https://github.com/addy-dclxvi/void-bspwm-dotfiles/blob/master/home/addy/.scripts/paintee

# Paintee
# A script to get colours from xrdb & deploy it to cache
# Then refresh URxvt colour on the fly
# Cheers! Addy

getcolors () {
	FOREGROUND="$(xrdb -query | grep 'foreground:'| awk '{print $NF}')"
	BACKGROUND="$(xrdb -query | grep 'background:'| awk '{print $NF}')"
	CURSOR="$(xrdb -query | grep 'cursorColor:'| awk '{print $NF}')"
	BLACK="$(xrdb -query | grep 'color0:'| awk '{print $NF}')"
	RED="$(xrdb -query | grep 'color1:'| awk '{print $NF}')"
	GREEN="$(xrdb -query | grep 'color2:'| awk '{print $NF}')"
	YELLOW="$(xrdb -query | grep 'color3:'| awk '{print $NF}')"
	BLUE="$(xrdb -query | grep 'color4:'| awk '{print $NF}')"
	MAGENTA="$(xrdb -query | grep 'color5:'| awk '{print $NF}')"
	CYAN="$(xrdb -query | grep 'color6:'| awk '{print $NF}')"
	WHITE="$(xrdb -query | grep 'color7:'| awk '{print $NF}')"
	ALTBLACK="$(xrdb -query | grep 'color8:'| awk '{print $NF}')"
	ALTRED="$(xrdb -query | grep 'color9:'| awk '{print $NF}')"
	ALTGREEN="$(xrdb -query | grep 'color10:'| awk '{print $NF}')"
	ALTYELLOW="$(xrdb -query | grep 'color11:'| awk '{print $NF}')"
	ALTBLUE="$(xrdb -query | grep 'color12:'| awk '{print $NF}')"
	ALTMAGENTA="$(xrdb -query | grep 'color13:'| awk '{print $NF}')"
	ALTCYAN="$(xrdb -query | grep 'color14:'| awk '{print $NF}')"
	ALTWHITE="$(xrdb -query | grep 'color15:'| awk '{print $NF}')"
}

cachecolors () {
	read -d '' cache <<- EOF
	FOREGROUND="${FOREGROUND}"
	BACKGROUND="${BACKGROUND}"
	CURSOR="${CURSOR}"
	BLACK="${BLACK}"
	RED="${RED}"
	GREEN="${GREEN}"
	YELLOW="${YELLOW}"
	BLUE="${BLUE}"
	MAGENTA="${MAGENTA}"
	CYAN="${CYAN}"
	WHITE="${WHITE}"
	ALTBLACK="${BLACK}"
	ALTRED="${RED}"
	ALTGREEN="${GREEN}"
	ALTYELLOW="${YELLOW}"
	ALTBLUE="${BLUE}"
	ALTMAGENTA="${MAGENTA}"
	ALTCYAN="${CYAN}"
	ALTWHITE="${WHITE}"
	EOF
}

main () {
	if [ -e ~/.cache/xcolors ]; then
	rm ~/.cache/xcolors
	fi

	getcolors
	cachecolors
	echo "$cache" > ~/.cache/xcolors
}

main
