(defvar treesit-language-source-alist
      '(
	(bash "https://github.com/tree-sitter/tree-sitter-bash")
	(bibtex "https://github.com/latex-lsp/tree-sitter-bibtex")
	(c "https://github.com/tree-sitter/tree-sitter-c")
	(cmake "https://github.com/uyha/tree-sitter-cmake")
	(comment "https://github.com/stsewd/tree-sitter-comment")
	(cpp "https://github.com/tree-sitter/tree-sitter-cpp")
	(css "https://github.com/tree-sitter/tree-sitter-css")
	(diff "https://github.com/the-mikedavis/tree-sitter-diff")
	(dockerfile "https://github.com/camdencheek/tree-sitter-dockerfile")
	(fish "https://github.com/ram02z/tree-sitter-fish")
	(go "https://github.com/tree-sitter/tree-sitter-go")
	(graphql "https://github.com/bkegley/tree-sitter-graphql")
	(html "https://github.com/tree-sitter/tree-sitter-html")
	(http "https://github.com/rest-nvim/tree-sitter-http")
	(java "https://github.com/tree-sitter/tree-sitter-java")
	(javascript "https://github.com/tree-sitter/tree-sitter-javascript")
	(jsdoc "https://github.com/tree-sitter/tree-sitter-jsdoc")
	(json "https://github.com/tree-sitter/tree-sitter-json")
	(jsonc "https://gitlab.com/WhyNotHugo/tree-sitter-jsonc.git")
	(latex "https://github.com/latex-lsp/tree-sitter-latex")
	(lua "https://github.com/MunifTanjim/tree-sitter-lua")
	(luadoc "https://github.com/amaanq/tree-sitter-luadoc")
	(luap "https://github.com/amaanq/tree-sitter-luap")
	(make "https://github.com/alemuller/tree-sitter-make")
	(markdown "https://github.com/MDeiml/tree-sitter-markdown" "split_parser" "tree-sitter-markdown/src")
	(markdown_inline "https://github.com/MDeiml/tree-sitter-markdown" "split_parser" "tree-sitter-markdown-inline/src")
	(perl "https://github.com/tree-sitter-perl/tree-sitter-perl" "release")
	(php "https://github.com/tree-sitter/tree-sitter-php")
	(python "https://github.com/tree-sitter/tree-sitter-python")
	(query "https://github.com/nvim-treesitter/tree-sitter-query")
	(r "https://github.com/r-lib/tree-sitter-r")
	(rasi "https://github.com/Fymyte/tree-sitter-rasi")
	(regex "https://github.com/tree-sitter/tree-sitter-regex")
	(ruby "https://github.com/tree-sitter/tree-sitter-ruby")
	(rust "https://github.com/tree-sitter/tree-sitter-rust")
	(scss "https://github.com/serenadeai/tree-sitter-scss")
	(tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
	(typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
	(vim "https://github.com/neovim/tree-sitter-vim")
	(vimdoc "https://github.com/neovim/tree-sitter-vimdoc")
	(vue "https://github.com/ikatyang/tree-sitter-vue")
	(xml "https://github.com/ObserverOfTime/tree-sitter-xml" "master" "tree-sitter-xml/src")
	(yaml "https://github.com/ikatyang/tree-sitter-yaml")
	(zig "https://github.com/maxxnino/tree-sitter-zig")))
(setq treesit-load-name-override-list '((js "libtree-sitter-js" "tree_sitter_javascript")))
(defun dotfiles/install-treesitter-grammars ()
  "Function to install (or update) treesitter grammars."
  (interactive)
  (mapc #'treesit-install-language-grammar (mapcar #'car treesit-language-source-alist)))
;;; init-treesitter.el ends here

