#!/usr/bin/env bash
#shellcheck disable=1090

source ~/dotfiles/conf/xorg/xinit-common
dex -a
picom --experimental-backends -b --config ~/dotfiles/conf/picom/ratpoison.conf

source ~/dotfiles/conf/xorg/xinit.d/no-xfce4
source ~/dotfiles/conf/xorg/xinit.d/dunst
source ~/dotfiles/conf/xorg/xinit.d/no-powerbutton
source ~/dotfiles/conf/xorg/xinit.d/dotfiles-media
source ~/dotfiles/conf/xorg/xinit.d/tile-background

# Load Bar
source ~/.cache/wal/colors.sh
pkill lemonaid; pkill lemonbar
# shellcheck disable=2154
lemonaid | lemonbar \
	-a 20 \
	-p -d \
	-f "JetBrains Mono Nerd Font:style=medium:size=10" \
	-B "$color0" \
	-F "$color7" \
	-g x22 | /usr/bin/env bash &

# vim:ft=sh
