use_nerdfont = true
notify = false
volnorm = true
repeat = "playlist"

[theme]

background = "black"
primary = "light white"
secondary = "light white"
title = "yellow"
playing = "yellow"
playing_bg = "black"
highlight = "light white"
highlight_bg = "#484848"
error = "light white"
error_bg = "red"
statusbar = "light yellow"
statusbar_progress = "blue"
statusbar_bg = "black"
cmdline = "light black"
cmdline_bg = "black"

[keybindings]
"," = "previous"
"." = "next"
"Ctrl+q" = "quit"
"q" = "back"
