use_nerdfont = true
notify = false
volnorm = true

[theme]

highlight = "light black"
highlight_bg = "#aeadaf"

[keybindings]
"Space" = "playpause"
"," = "previous"
"." = "next"
"Ctrl+q" = "quit"
"q" = "move up 1"
