#!/usr/bin/env bash
#
source ~/dotfiles/conf/xorg/xinit-common
source ~/dotfiles/conf/xorg/xprofile-common

hsetroot -cover ~/dotfiles/backgrounds/wallhaven-nml81k.jpg

dunst &
killall -q polybar
liskin-media mpris-daemon&

# Launch bar1 and bar2
echo "---" | tee -a /tmp/polybar1.log /tmp/polybar2.log
polybar switcher 2>&1 | tee -a /tmp/polybar1.log & disown
polybar tray 2>&1 | tee -a /tmp/polybar2.log & disown

# vim:ft=sh
