#!/usr/bin/env bash
#
picom --experimental-backends -b --config ~/dotfiles/conf/picom/common.conf

source ~/dotfiles/conf/xorg/xinit-common

hsetroot -cover ~/dotfiles/backgrounds/wallhaven-nml81k.jpg
# vim:ft=sh
