# Builtin Dark
[colors]
foreground = "{color15}"
background = "{color0}"
cursor_bg = "{color7}"
cursor_border = "{color7}"
cursor_fg = "{color0}"
selection_bg = "{color15}"
selection_fg = "{color0}"

ansi = ["{color0}","{color1}","{color2}","{color3}","{color4}","{color5}","{color6}","{color7}"]
brights = ["{color8}","{color9}","{color10}","{color11}","{color12}","{color13}","{color14}","{color15}"]
