# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """
$hostname\
$username\
$shell\
$nodejs\
$ruby\
$python\
$directory\
$git_branch\
$git_state\
$git_status\
$status\
$character"""

[character]
format = " $symbol "
success_symbol = "λ"
error_symbol = "[λ](red)"

[status]
format = "[\\[$symbol$status\\]]($style)"
disabled = false
symbol = ""
style = "red"

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
truncate_to_repo = false
style = "cyan"
repo_root_style = "bold cyan"
fish_style_pwd_dir_length = 1

[git_branch]
format = "\\([$branch]($style)"

[git_status]
format = "[$all_status$ahead_behind]($style)\\)"
ahead = "|↑$count"
behind = "|↓$count"
conflicted = "|[=$count](bold purple)"
diverged = "|↑$ahead_count↓$behind_count"
deleted = "|[x$count](bold red)"
modified = "|[+$count](bold blue)"
staged = "|[●$count](bold yellow)"
stashed = ""
style = ""
untracked ="|…"
up_to_date = ""

[hostname]
ssh_only = true
ssh_symbol = "[SSH](bold yellow)"
format = "$ssh_symbol@[$hostname:](yellow)"

[nodejs]
symbol = ""
format = "[$symbol($version):]($style)"
version_format = "${raw}"
style = "blue"
detect_extensions = []

[ruby]
symbol = ""
format = "[$symbol($version):]($style)"
version_format = "${raw}"
style = "blue"
detect_extensions = []

[python]
symbol = ""
format = "[$symbol(($pyenv_prefix)$version(;$virtualenv)):]($style)"
version_format = "${raw}"
style = "blue"
detect_extensions = []

[username]
format="[$user:]($style)"

[shell]
disabled = false
fish_indicator = ""
bash_indicator = "bash:"
zsh_indicator = "zsh:"
powershell_indicator = "psh:"
ion_indicator = "ion:"
elvish_indicator = "esh:"
tcsh_indicator = "tcsh:"
xonsh_indicator = "xonsh:"
cmd_indicator = "cmd:"
nu_indicator = "nu:"
format = "[$indicator]($style)"
style = "green"

### UNUSED ####################################################################
[localip]
disabled = true
[shlvl]
disabled = true
[singularity]
disabled = true
[kubernetes]
disabled = true
[vcsh]
disabled = true
[git_commit]
disabled = true
[git_metrics]
disabled = true
[hg_branch]
disabled = true
[docker_context]
disabled = true
[package]
disabled = true
[buf]
disabled = true
[c]
disabled = true
[cmake]
disabled = true
[cobol]
disabled = true
[container]
disabled = true
[daml]
disabled = true
[dart]
disabled = true
[deno]
disabled = true
[dotnet]
disabled = true
[elixir]
disabled = true
[elm]
disabled = true
[erlang]
disabled = true
[golang]
disabled = true
[haskell]
disabled = true
[helm]
disabled = true
[java]
disabled = true
[julia]
disabled = true
[kotlin]
disabled = true
[lua]
disabled = true
[nim]
disabled = true
[ocaml]
disabled = true
[perl]
disabled = true
[php]
disabled = true
[pulumi]
disabled = true
[purescript]
disabled = true
[rlang]
disabled = true
[red]
disabled = true
[rust]
disabled = true
[scala]
disabled = true
[swift]
disabled = true
[terraform]
disabled = true
[vlang]
disabled = true
[vagrant]
disabled = true
[zig]
disabled = true
[nix_shell]
disabled = true
[conda]
disabled = true
[spack]
disabled = true
[memory_usage]
disabled = true
[aws]
disabled = true
[gcloud]
disabled = true
[openstack]
disabled = true
[azure]
disabled = true
[crystal]
disabled = true
[cmd_duration]
disabled = true
[line_break]
disabled = true
[jobs]
disabled = true
[battery]
disabled = true
[time]
disabled = true
