-- luacheck: globals vim
local get_wal_theme = require('dotfiles.utils.wal')
local json_scheme = get_wal_theme()
local wal = {
	color0 = { c = 0, gui = json_scheme.colors.color0 and json_scheme.colors.color0 or "#000000" },
	color1 = { c = 1, gui = json_scheme.colors.color1 and json_scheme.colors.color1 or "#FF0000" },
	color2 = { c = 2, gui = json_scheme.colors.color2 and json_scheme.colors.color2 or "#00FF00" },
	color3 = { c = 3, gui = json_scheme.colors.color3 and json_scheme.colors.color3 or "#FFFF00" },
	color4 = { c = 4, gui = json_scheme.colors.color4 and json_scheme.colors.color4 or "#0000FF" },
	color5 = { c = 5, gui = json_scheme.colors.color5 and json_scheme.colors.color5 or "#FF00FF" },
	color6 = { c = 6, gui = json_scheme.colors.color6 and json_scheme.colors.color6 or "#00FFFF" },
	color7 = { c = 7, gui = json_scheme.colors.color7 and json_scheme.colors.color7 or "#000000" },
	color8 = { c = 8, gui = json_scheme.colors.color8 and json_scheme.colors.color8 or "#FFFFFF" },
	color9 = { c = 9, gui = json_scheme.colors.color9 and json_scheme.colors.color9 or "#FF0000" },
	color10 = { c = 10, gui = json_scheme.colors.color10 and json_scheme.colors.color10 or "#00FF00" },
	color11 = { c = 11, gui = json_scheme.colors.color11 and json_scheme.colors.color11 or "#FFFF00" },
	color12 = { c = 12, gui = json_scheme.colors.color12 and json_scheme.colors.color12 or "#0000FF" },
	color13 = { c = 13, gui = json_scheme.colors.color13 and json_scheme.colors.color13 or "#FF00FF" },
	color14 = { c = 14, gui = json_scheme.colors.color14 and json_scheme.colors.color14 or "#00FFFF" },
	color15 = { c = 15, gui = json_scheme.colors.color15 and json_scheme.colors.color15 or "#FFFFFF" },
}

function wal.terminal_colors()
	vim.g.terminal_color_0 = wal.color0.gui
	vim.g.terminal_color_1 = wal.color1.gui
	vim.g.terminal_color_2 = wal.color2.gui
	vim.g.terminal_color_3 = wal.color3.gui
	vim.g.terminal_color_4 = wal.color4.gui
	vim.g.terminal_color_5 = wal.color5.gui
	vim.g.terminal_color_6 = wal.color6.gui
	vim.g.terminal_color_7 = wal.color7.gui
	vim.g.terminal_color_8 = wal.color8.gui
	vim.g.terminal_color_9 = wal.color9.gui
	vim.g.terminal_color_10 = wal.color10.gui
	vim.g.terminal_color_11 = wal.color11.gui
	vim.g.terminal_color_12 = wal.color12.gui
	vim.g.terminal_color_13 = wal.color13.gui
	vim.g.terminal_color_14 = wal.color14.gui
	vim.g.terminal_color_15 = wal.color15.gui
end
function wal.highlight(group, color)
	if color.link then
		vim.api.nvim_command('highlight default link ' .. group .. ' ' .. color.link)
		return
	end
	local style = color.style and 'gui=' .. color.style or 'gui=NONE'
	local term_style = color.term and ' term=' .. color.term or 'term=NONE'
	local fg = color.fg and 'guifg=' .. color.fg.gui .. ' ctermfg=' .. color.fg.c or 'guifg=NONE ctermfg=NONE'
	local bg = color.bg and 'guibg=' .. color.bg.gui .. ' ctermbg=' .. color.bg.c or 'guibg=NONE ctermbg=NONE'
	local sp = color.sp and 'guisp=' .. color.sp.gui or ''
   vim.api.nvim_command(
		'highlight ' .. group .. ' ' ..
		style .. ' ' ..
		term_style .. ' ' ..
		fg .. ' ' ..
		bg .. ' ' ..
		sp
	)
end
function wal.after_scheme()
	local scheme = {
		RedSign = {fg=wal.color5, bg=wal.color8},
		YellowSign = {fg=wal.color3, bg=wal.color8},
		BlueSign = {fg=wal.color4, bg=wal.color8},
		GreenSign = {fg=wal.color2, bg=wal.color8},
		Orange = {fg=wal.color1},
		Green = {fg=wal.color2},
		Yellow = {fg=wal.color3},
		Blue = {fg=wal.color4},
		Red = {fg=wal.color5},
		Cyan = {fg=wal.color6},
		Grey = {fg=wal.color7},
		OrangeBright = {fg=wal.color9},
		GreenBright = {fg=wal.color10},
		YellowBright = {fg=wal.color11},
		BlueBright = {fg=wal.color12},
		RedBright = {fg=wal.color13},
		CyanBright = {fg=wal.color14},
		Fg = {fg=wal.color15},
		OrangeEmphasis = {fg=wal.color1, style="bold"},
		GreenEmphasis = {fg=wal.color2, style="bold"},
		YellowEmphasis = {fg=wal.color3, style="bold"},
		BlueEmphasis = {fg=wal.color4, style="bold"},
		RedEmphasis = {fg=wal.color5, style="bold"},
		CyanEmphasis = {fg=wal.color6, style="bold"},
		GreyEmphasis = {fg=wal.color7, style="bold"},
		OrangeBrightEmphasis = {fg=wal.color9, style="bold"},
		GreenBrightEmphasis = {fg=wal.color10, style="bold"},
		YellowBrightEmphasis = {fg=wal.color11, style="bold"},
		BlueBrightEmphasis = {fg=wal.color12, style="bold"},
		RedBrightEmphasis = {fg=wal.color13, style="bold"},
		CyanBrightEmphasis = {fg=wal.color14, style="bold"},
		FgEmphasis = {fg=wal.color15, style="bold"},
		OrangeItalic = {fg=wal.color1, style="italic"},
		GreenItalic = {fg=wal.color2, style="italic"},
		YellowItalic = {fg=wal.color3, style="italic"},
		BlueItalic = {fg=wal.color4, style="italic"},
		RedItalic = {fg=wal.color5, style="italic"},
		CyanItalic = {fg=wal.color6, style="italic"},
		GreyItalic = {fg=wal.color7, style="italic"},
		OrangeBrightItalic = {fg=wal.color9, style="italic"},
		GreenBrightItalic = {fg=wal.color10, style="italic"},
		YellowBrightItalic = {fg=wal.color11, style="italic"},
		BlueBrightItalic = {fg=wal.color12, style="italic"},
		RedBrightItalic = {fg=wal.color13, style="italic"},
		CyanBrightItalic = {fg=wal.color14, style="italic"},
		FgItalic = {fg=wal.color15, style="italic"},
		ErrorFloat = { link = "RedSign" },
		WarningFloat = { link = "YellowSign" },
		InfoFloat = { link = "BlueSign" },
		HintFloat = { link = "GreenSign" },
		ErrorText = { link = "RedSign" },
		WarningText = { link = "YellowSign" },
		InfoText = { link = "BlueSign" },
		HintText = { link = "GreenSign" },
		LspDiagnosticsFloatingError = { link = "ErrorFloat" },
		LspDiagnosticsFloatingWarning = { link = "WarningFloat" },
		LspDiagnosticsFloatingInformation = { link = "InfoFloat" },
		LspDiagnosticsFloatingHint = { link = "HintFloat" },
		LspDiagnosticsDefaultError = { link = "ErrorText" },
		LspDiagnosticsDefaultWarning = { link = "WarningText" },
		LspDiagnosticsDefaultInformation = { link = "InfoText" },
		LspDiagnosticsDefaultHint = { link = "HintText" },
		LspDiagnosticsVirtualTextError = { link = "Grey" },
		LspDiagnosticsVirtualTextWarning = { link = "Grey" },
		LspDiagnosticsVirtualTextInformation = { link = "Grey" },
		LspDiagnosticsVirtualTextHint = { link = "Grey" },
		LspDiagnosticsUnderlineError = { link = "ErrorText" },
		LspDiagnosticsUnderlineWarning = { link = "WarningText" },
		LspDiagnosticsUnderlineInformation = { link = "InfoText" },
		LspDiagnosticsUnderlineHint = { link = "HintText" },
		LspDiagnosticsSignError = { link = "RedSign" },
		LspDiagnosticsSignWarning = { link = "YellowSign" },
		LspDiagnosticsSignInformation = { link = "BlueSign" },
		LspDiagnosticsSignHint = { link = "GreenSign" },
		LspReferenceText = { link = "CurrentWord" },
		LspReferenceRead = { link = "CurrentWord" },
		LspReferenceWrite = { link = "CurrentWord" },
		TermCursor = { link = "Cursor" },
		healthError = { link = "Red" },
		healthSuccess = { link = "Green" },
		healthWarning = { link = "Yellow" },
		TSAnnotation = { link = "Blue" },
		TSAttribute = { link = "Blue" },
		TSBoolean = { link = "BlueBright" },
		TSCharacter = { link = "Yellow" },
		TSComment = { link = "Grey" },
		TSConditional = { link = "Red" },
		TSConstBuiltin = { link = "Orange" },
		TSConstMacro = { link = "Orange" },
		TSConstant = { link = "Orange" },
		TSConstructor = { link = "Fg" },
		TSError = { link = "ErrorText" },
		TSException = { link = "Red" },
		TSField = { link = "Green" },
		TSFloat = { link = "BlueBright" },
		TSFuncBuiltin = { link = "OrangeBright" },
		TSFuncMacro = { link = "OrangeBright" },
		TSFunction = { link = "OrangeBright" },
		TSInclude = { link = "OrangeBright" },
		TSKeyword = { link = "CyanEmphasis" },
		TSKeywordFunction = { link = "Cyan" },
		TSLabel = { link = "Red" },
		TSMethod = { link = "Green" },
		TSNamespace = { link = "BlueBright" },
		TSNumber = { link = "BlueBright" },
		TSOperator = { link = "Red" },
		TSParameter = { link = "Orange" },
		TSParameterReference = { link = "Orange" },
		TSProperty = { link = "Green" },
		TSPunctBracket = { link = "Fg" },
		TSPunctDelimiter = { link = "Grey" },
		TSPunctSpecial = { link = "Fg" },
		TSRepeat = { link = "Red" },
		TSString = { link = "BlueBright" },
		TSStringEscape = { link = "Green" },
		TSStringRegex = { link = "Green" },
		TSStructure = { link = "Blue" },
		TSTag = { link = "Blue" },
		TSTagDelimiter = { link = "Red" },
		TSText = { link = "Green" },
		TSEmphasis = {style="bold"},
		TSUnderline = {style="underline"},
		TSType = { link = "Blue" },
		TSTypeBuiltin = { link = "Blue" },
		TSURI = { link = "markdownUrl" },
		TSVariable = { link = "Fg" },
		TSVariableBuiltin = { link = "Orange" },
		DiffAdd = {style="bold", bg=wal.color2, fg=wal.background},
		DiffDelete = {style="none", bg=wal.color1, fg=wal.background},
		DiffChange = {style="bold", bg=wal.color8, fg=wal.color7},
		DiffText = {style="bold", bg=wal.color8, fg=wal.color9},
		diffAdded = {fg=wal.color2},
		diffRemoved = {fg=wal.color1},
		diffNewFile = {style="none", fg=wal.color4},
		diffFile = {style="none", fg=wal.color3},
		GitGutterAdd = {bg=wal.color8, fg=wal.color2},
		GitGutterChange = {style="bold", bg=wal.color8, fg=wal.color7},
		GitGutterDelete = {bg=wal.color8, fg=wal.color1},
		GitGutterChangeDelete = {style="bold", bg=wal.color8, fg=wal.color1},
		NeomakeError = {style="none", bg=wal.color1, fg=wal.background},
		NeomakeInfo = {style="none", bg=wal.color6, fg=wal.background},
		NeomakeWarning = {style="none", bg=wal.color3, fg=wal.background},
		NeomakeMessage = {style="none", bg=wal.color11, fg=wal.background},
		NeomakeVirtualtextInfoDefault = {fg=wal.color14},
		NeomakeVirtualtextMessageDefault = {fg=wal.color11},
		NeomakeVirtualtextWarningDefault = {fg=wal.color3},
		NeomakeVirtualtextErrorDefault = {fg=wal.color1},
		NeomakeStatusGood = {style="none", bg=wal.color2, fg=wal.background},
		NeomakeStatusGoodNC = {style="none", bg=wal.color8, fg=wal.color2},
		NeomakeStatColorDefault = {style="none", bg=wal.color4, fg=wal.background},
		NeomakeStatColorTypeE = {style="none", bg=wal.color1, fg=wal.background},
		NeomakeStatColorTypeW = {style="none", bg=wal.color3, fg=wal.background},
		MarkdownRule = {style="bold", bg=wal.color8, fg=wal.color10},
		MarkdownHeading = {style="bold", fg=wal.foreground},
		MarkdownH1 = { link = "MarkdownHeading" },
		MarkdownH2 = { link = "MarkdownHeading" },
		MarkdownH3 = { link = "MarkdownHeading" },
		MarkdownH4 = { link = "MarkdownHeading" },
		MarkdownH5 = { link = "MarkdownHeading" },
		MarkdownH6 = { link = "MarkdownHeading" },
		MarkdownHeadingDelimiter = { link = "MarkdownHeading" },
		MarkdownHeadingRule = { link = "MarkdownHeading" },
		MarkdownBold = {style="bold", fg=wal.color9},
		MarkdownBoldDelimiter = { link = "MarkdownBold" },
		MarkdownItalic = {style="italic", fg=wal.color3},
		MarkdownItalicDelimiter = { link = "MarkdownItalic" },
		MarkdownUrl = {style="underline", fg=wal.color4},
		MarkdownLinkText = {style="none", fg=wal.color12},
		MarkdownLinkDelimiter = {style="bold", fg=wal.foreground},
		MarkdownLinkTextDelimiter = { link = "MarkdownLinkDelimiter" },
		MarkdownCode = {fg=wal.color5},
		MarkdownCodeDelimiter = { link = "MarkdownCode" },
		MarkdownCodeBlock = {fg=wal.foreground},
		MarkdownListMarker = {style="none", fg=wal.color2},
		MarkdownOrderedListMarker = { link = "MarkdownListMarker" },
		YcmErrorSection = {style="undercurl", sp=wal.color1},
		YcmWarningSection = {style="undercurl", sp=wal.color3},
		SyntasticError = {style="undercurl", sp=wal.color1},
		SyntasticWarning = {style="undercurl", sp=wal.color3},
		SyntasticErrorSing = {fg=wal.background, bg=wal.color1},
		SyntasticWarningSign = {fg=wal.background, bg=wal.color3},
		Visual = {bg=wal.color12},
		Search = {bg=wal.color3, fg=wal.background},
		gitcommitSummary = {fg=wal.color14},
		gitcommitOverflow = {style="bold", bg=wal.color13, fg=wal.background},
		IncSearch = {bg=wal.color9, fg=wal.background},
		HighlightedyankRegion = {bg=wal.color9, fg=wal.background},
		CocErrorSign = {bg=wal.color8, fg=wal.color1},
		CocWarningSign = {bg=wal.color8, fg=wal.color3},
		CocInfoSign = {bg=wal.color8, fg=wal.color1},
		ALEErrorSign = {bg=wal.color1, fg=wal.color8},
		ALEWarningSign = {bg=wal.color3, fg=wal.color8},
		ALEInfoSign = {bg=wal.color8, fg=wal.color7},
		VisualMode = {fg=wal.background, bg=wal.color9, style="bold"},
		InsertMode = {fg=wal.background, bg=wal.color2, style="bold"},
		ReplaceMode = {fg=wal.background, bg=wal.color13, style="bold"},
		CommandMode = {fg=wal.background, bg=wal.color6, style="bold"},
		TerminalMode = {fg=wal.background, bg={ gui="#CC9CCF", c=182 }, style="bold"},
		NormalMode = {fg=wal.background, bg=wal.color4, style="bold"},
		VisualModeInv = {fg=wal.color9, bg=wal.background},
		InsertModeInv = {fg=wal.color2, bg=wal.background},
		ReplaceModeInv = {fg=wal.color13, bg=wal.background},
		CommandModeInv = {fg=wal.color6, bg=wal.background},
		TerminalModeInv = {fg=wal.color12, bg=wal.background},
		NormalModeInv = {fg=wal.color4, bg=wal.background},
		StatusLine = {fg=wal.color8},
		StatusLineNC = {fg=wal.color11, bg=wal.color8},
		StatusLineTerm = {fg=wal.color10, bg=wal.color2},
		StatusLineTermNC = {fg=wal.color11, bg=wal.color8},
		User1 = {fg=wal.color7, bg=wal.color8},
		User2 = { link = "Normal" },
		StatusWarning = {fg=wal.color8, bg=wal.color3},
		StatusError = {fg=wal.color8, bg=wal.color1},
		StatusOk = {fg=wal.foreground, bg=wal.color8},
		StatusWarningInv = {bg=wal.background, fg=wal.color3},
		StatusErrorInv = {bg=wal.background, fg=wal.color1},
		StatusOkInv = {bg=wal.background, fg=wal.color8},
		StatusInfoInv = {fg=wal.color8, bg=wal.background},
		StatusLineInfo = {fg=wal.foreground, bg={ gui = "#4a4a4b", c = 238 }},
		StatusLineInfoInv = {fg={ gui = "#4a4a4b", c = 238 }, bg=wal.background},
		SpellBad = {style="underline", fg=wal.foreground, bg=wal.color8, sp=wal.color13},
		ALEError = {style="underline", fg=wal.foreground, bg=wal.color8, sp=wal.color1},
		ALEWarning = {style="underline", fg=wal.foreground, bg=wal.color8, sp=wal.color3},
		Pmenu = {style="none", bg=wal.color8, fg=wal.foreground},
		MarkdownItalic = {fg=wal.color13},
		htmlItalic = { link = "MarkdownItalic" },
		htmlBold = { link = "MarkdownBold" },
		mkdBlockquote = {style="italic", fg=wal.color7},
		semshiLocal = { fg={ gui = "#ff875f", c=209 }},
		semshiGlobal = { fg=wal.color1},
		semshiImported = { fg={ gui = "#ffaf00", c=214 }, style="bold"},
		semshiParameter = { fg=wal.color4},
		semshiParameterUnused = {fg=wal.color12, style="underline"},
		semshiFree = { fg=wal.color5},
		semshiBuiltin = { fg=wal.color13},
		semshiAttribute = { fg=wal.color6},
		semshiSelf = { fg=wal.color7},
		semshiUnresolved = { fg=wal.color3, style="underline"},
		semshiSelected = { fg=wal.background, bg={ gui = "#ff875f", c=209 }},
	   semshiErrorSign = { fg=wal.foreground, bg={ gui = "#d70000", c=160 }},
	   semshiErrorChar = { fg=wal.foreground, bg={ gui = "#d70000", c=160 }},
	}
	return scheme
end
function wal.scheme()
	local scheme = {
		 Normal = {bg=wal.background, fg=wal.foreground},
		 Visual = {bg=wal.foreground, fg=wal.background},
		 Search = {style="underline,bold", bg=wal.color8, fg=wal.foreground, term="bold"},
		 IncSearch = {style="underline,bold", bg=wal.color7, fg=wal.background, term="none,bold"},
		 VertSplit = {style="none"},
		 TabLine = {style="none", bg=wal.color8, fg=wal.color7},
		 TabLineSel = {style="none", bg=wal.color6, fg=wal.background},
		 TabLineFill = {style="none"},
		 Comment = {style="italic", fg=wal.color7},
		 Todo = {style="bold", bg=wal.color8, fg=wal.color11},
		 Warning = {style="none", bg=wal.color3, fg=wal.background},
		 WarningMsg = {style="none", bg=wal.color3, fg=wal.background},
		 Error = {style="none", bg=wal.color1, fg=wal.background},
		 ErrorMsg = {style="none", bg=wal.color1, fg=wal.background},
		 MatchParen = {style="underline,bold", bg=wal.color8, fg=wal.color7, term="bold"},
		 ToolbarLine = {bg=wal.color7, fg=wal.background, term="none"},
		 ToolbarButton = {style="bold", bg=wal.color7, fg=wal.background, term="none"},
		 WildMenu = {bg=wal.background, fg=wal.foreground, term="standout"},
		 Terminal = {bg=wal.background, fg=wal.foreground, term="none"},
		 constant = {fg=wal.color4},
		 Number = {fg=wal.color4},
		 Float = {fg=wal.color4},
		 String = {fg=wal.color12},
		 Function = {fg=wal.color5},
		 Identifier = {fg=wal.color13, term="none"},
		 Label = {fg=wal.color5},
		 Tag = {fg=wal.color5},
		 Keyword = {fg=wal.color13, style="bold"},
		 Character = {style="bold", fg=wal.color14},
		 Type = {style="none,bold", fg=wal.color6, term="none,bold"},
		 Boolean = {fg=wal.color6},
		 StorageClass = {fg=wal.color6},
		 Structure = {fg=wal.color6},
		 Typedef = {style="bold", fg=wal.color14},
		 Conditional = {style="bold", fg=wal.color2},
		 Statement = {style="none", fg=wal.color10},
		 Repeat = {style="bold", fg=wal.color10},
		 Operator = {style="bold", fg=wal.foreground},
		 Exception = {style="bold", fg=wal.color1},
		 Preproc = {style="none", fg=wal.color9, term="none"},
		 PreCondit = {style="bold", fg=wal.color9},
		 Macro = {style="bold", fg=wal.color9},
		 Include = {fg=wal.color9},
		 Define = {fg=wal.color9},
		 Title = {style="bold", bg=wal.background, fg=wal.color6},
		 Delimeter = {style="bold", fg=wal.color5},
		 Delimiter = {style="bold", fg=wal.color5},
		 SpecialComment = {style="bold", fg=wal.color5},
		 Debug = {fg=wal.color13},
		 LineNr = {bg=wal.color8, fg=wal.color7, term="none"},
		 Cursor = {bg=wal.foreground, fg=wal.background},
		 CursorLine = {style="none", bg=wal.color8, term="none"},
		 CursorColumn = {style="none", bg=wal.color8, term="none"},
		 CursorLineNr = {style="bold", bg=wal.color7, fg=wal.background},
		 ColorColumn = {bg=wal.color8, fg=wal.foreground, term="none"},
		 SignColumn = {bg=wal.color8, fg=wal.color7, term="none"},
		 Folded = {bg=wal.color8, fg=wal.color7},
		 FoldColumn = {bg=wal.color8, fg=wal.color7},
		 Special = {style="bold", fg=wal.color11, term="none"},
		 SpecialKey = {style="none", bg=wal.color8, fg=wal.color7},
		 SpecialChar = {style="bold", fg=wal.color11},
		 NonText = {style="none", bg=wal.color8, fg=wal.color7},
		 EndOfBuffer = {style="bold", fg=wal.color7},
		 Directory = {style="none", fg=wal.color2, term="none"},
		 Question = {style="bold", fg=wal.color11},
		 MoreMsg = {fg=wal.color10},
		 ModeMsg = {style="bold", fg=wal.color2},
		 VimOption = {fg=wal.color5},
		 VimGroup = {fg=wal.color5},
		 Underlined = {style="underline", fg=wal.foreground},
		 Ignore = {bg=wal.color8, fg=wal.color7},
		 Conceal = {fg={ gui="Grey30", c=239 }, style="nocombine"},
		 SpellBad = {bg=wal.color1, fg=wal.background},
		 SpellCap = {bg=wal.color3, fg=wal.background},
		 SpellRare = {bg=wal.color13, fg=wal.background},
		 SpellLocal = {bg=wal.color14, fg=wal.background},
		 Pmenu = {style="italic", bg=wal.color8, fg=wal.foreground},
		 PmenuSel = {style="none,bold", bg=wal.color7, fg=wal.background, term="bold"},
		 PmenuSbar = {bg=wal.color8},
		 PmenuThumb = {bg=wal.color7},
	}
	return scheme
end
local async_load_plugin
async_load_plugin = vim.loop.new_async(vim.schedule_wrap(function ()
	wal.terminal_colors()
	local syntax = wal.after_scheme()
	for group,colors in pairs(syntax) do
		wal.highlight(group,colors)
	end
	async_load_plugin:close()
end))
function wal.colorscheme()
	vim.cmd('hi clear')
	if vim.fn.exists('syntax_on') then
		vim.cmd('syntax reset')
	end
	vim.o.background = 'dark'
	vim.o.termguicolors = true
	vim.g.colors_name = 'wal'
	local syntax = wal.scheme()
	for group,colors in pairs(syntax) do
		wal.highlight(group,colors)
	end
	async_load_plugin:send()
end

wal.colorscheme()

return wal
