#!/bin/sh

# Source Pywal:
. "${HOME}/.cache/wal/colors.sh"
# Launch sxhkd:
pgrep -x sxhkd > /dev/null || sxhkd &
# Launch polybar:
"$HOME"/dotfiles/scripts/polybar/launch &
# Configure desktops:
bspc monitor -d I II III IV V #VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config normal_border_color  "$background"
bspc config active_border_color  "$color8"
bspc config focused_border_color "$color4"
bspc config presel_feedback_color "$color3"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
# vim:ft=sh
