#!/usr/bin/env bash
# ~/.bashrc
#
DOTFILES_TARGET="$( [ -e ~/.local/share/dotfiles/target ] && /bin/cat ~/.local/share/dotfiles/target)"
export DOTFILES_TARGET

EDITOR="$(which nvim)"
export EDITOR

OW_KEY="$(cat ~/.ow_credentials.json | jq -r .key)"
OW_LAT="$(cat ~/.ow_credentials.json | jq .coordinates[0])"
OW_LONG="$(cat ~/.ow_credentials.json | jq .coordinates[1])"
export OW_KEY OW_LAT OW_LONG

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='exa --group-directories-first'
PS1='[\u@\h \W]\$ '

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
# vim:ft=sh
