#!/usr/bin/env bash
# ~/.bashrc
#
DOTFILES_TARGET="$( [ -e ~/.local/share/dotfiles/target ] && /bin/cat ~/.local/share/dotfiles/target)"
export DOTFILES_TARGET

EDITOR="$(which nvim)"
export EDITOR

if [ -e ~/.ow_credentials.json ]; then
	OW_KEY="$(jq -r .key ~/.ow_credentials.json)"
	OW_LAT="$(jq .coordinates[0] ~/.ow_credentials.json)"
	OW_LONG="$(jq .coordinates[1] ~/.ow_credentials.json)"
	export OW_KEY OW_LAT OW_LONG
fi

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='exa --group-directories-first'
PS1='[\u@\h \W]\$ '

[[ -d /opt/homebrew ]] && PATH="${PATH}:/opt/homebrew/bin"
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
if command -v starship > /dev/null; then
	eval "$(starship init bash)"
fi
# vim:ft=sh
