#!/usr/bin/env bash

source ~/dotfiles/conf/xorg/xinit-common
source ~/.cache/wal/colors.sh
xrdb -merge ~/.cache/wal/dwm.Xresources
xrdb -merge ~/.cache/wal/dmenu.Xresources

convert ~/.cache/wal/background.svg ~/.cache/wal/background.png
hsetroot -tile ~/.cache/wal/background.png

/usr/bin/picom --experimental-backends -b

dunst&

pkill dwmblocks
dwmblocks&
mkdir -p ~/.cache/dwm
exec dwm 2> ~/.cache/dwm/stderr

# vim:ft=sh
