#!/usr/bin/env bash

source ~/dotfiles/conf/xorg/xinit.d/no-xfce4

picom

DOTFILES_TARGET="$( [ -e ~/.local/share/dotfiles/target ] && /bin/cat ~/.local/share/dotfiles/target)"
if [ "$DOTFILES_TARGET" == "laptop" ]; then
	hsetroot -cover ~/dotfiles/backgrounds/wallhaven-nml81k.jpg
fi
# vim:ft=sh
