#!/usr/bin/env bash

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.
# Setting some startup stuff

riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"
riverctl spawn "river-init-mako.sh"
riverctl spawn "river-init-wlsunset.sh"
riverctl spawn "river-init-swaybg.sh"
riverctl spawn "river-init-media.sh"
riverctl spawn "river-init-waybar.sh"
riverctl spawn "river-init-swaylock.sh"

# Load Keybindings:
riverctl spawn "$HOME/.config/river/bindings.sh"

# Borders
source ~/.cache/wal/colors.sh
riverctl border-color-focused "${color6//#/}"
riverctl border-color-unfocused "${color0//#/}"
riverctl border-width 1
riverctl background-color "${color0//#/}"
