#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.
# Setting some startup stuff
riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"


# Binding to reload the configuration (good for edits on bindings or adding new stuff
riverctl map normal "Mod4" R spawn $HOME/.config/river/init

# Setting some startup stuff
riverctl spawn "river-tag-overlay --background-colour 0x1d2021 --border-colour 0xa9b665 --square-active-occupied-colour 0xd79921 --square-active-background-colour 0xa9b665 --square-active-border-colour 0xd4be98 --tag-amount 11"
riverctl spawn "wlsunset -l 8.17 -L 123.80"
riverctl spawn $HOME/.config/river/wlsunset.sh
riverctl spawn $HOME/.config/mako/mako.sh
riverctl spawn $HOME/.config/river/swaybg.sh
riverctl spawn $HOME/.config/river/bindings.sh
riverctl spawn $HOME/.config/eww/eww.sh
riverctl spawn $HOME/.local/share/bin/gtk.sh

# Borders
riverctl border-color-focused 0xfc7216
riverctl border-color-unfocused 0x92a58b
riverctl border-width 2
riverctl background-color 0x282828
