#!/usr/bin/env bash
riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"
# Startup:
for file in "$HOME"/.config/river/init.d/*; do
	riverctl spawn "$file"
done
# Configuration Files:
for file in "$HOME"/.config/river/config/*.sh; do
	riverctl spawn "$file"
done
# Load default layout:
riverctl spawn "$HOME/.config/river/utils/update_layout.sh tile"
