#!/usr/bin/env bash

if [ -a ~/.xinitrc.local ]; then
	# shellcheck source=/dev/null
	source ~/.xinitrc.local
else
	DESKTOP_SESSION=dwm
fi
export DESKTOP_SESSION

# shellcheck source=/dev/null
source ~/.xprofile

if [ -d /etc/X11/xinit/xinitrc.d/ ] ; then
	for f in /etc/X11/xinit/xinitrc.d/*.sh ; do
		# shellcheck source=/dev/null
		[ -f "$f" ] && . "$f"
	done
	unset f
fi

if [ "$DESKTOP_SESSION" = "xfce4" ]; then
	WM_EXEC=startxfce4
else
	WM_EXEC="$DESKTOP_SESSION"
fi

mkdir -p ~/.cache/"$DESKTOP_SESSION"
exec $WM_EXEC 2> ~/.cache/"$DESKTOP_SESSION"/stderr

# vim:ft=sh
