#!/usr/bin/env bash

if [ -a ~/.xinitrc.local ]; then
	# shellcheck source=/dev/null
	source ~/.xinitrc.local
else
	DESKTOP_SESSION=dwm
fi
export DESKTOP_SESSION

# shellcheck source=/dev/null
source ~/dotfiles/conf/xorg/xinit-common
source ~/dotfiles/conf/xorg/xprofile-common
# shellcheck source=/dev/null
[ -e ~/dotfiles/conf/xorg/xprofile.d/"$DESKTOP_SESSION" ] && source ~/dotfiles/conf/xorg/xprofile.d/"$DESKTOP_SESSION"

if [ -d /etc/X11/xinit/xinitrc.d/ ] ; then
	for f in /etc/X11/xinit/xinitrc.d/*.sh ; do
		# shellcheck source=/dev/null
		[ -f "$f" ] && . "$f"
	done
	unset f
fi

run_dex=1
if [ "$DESKTOP_SESSION" = "xfce4" ]; then
	WM_EXEC=startxfce4
	run_dex=0
else
	lxsession&
	WM_EXEC="$DESKTOP_SESSION"
fi

if [ "$run_dex" -eq 1 ]; then
	dex -a
fi

mkdir -p ~/.cache/"$DESKTOP_SESSION"
exec $WM_EXEC 2> ~/.cache/"$DESKTOP_SESSION"/stderr

# vim:ft=sh
