#!/bin/bash

# Source: https://raw.githubusercontent.com/Juicyexe/arch-monochrome/main/.config/polybar/scripts/sysmenu

# More Options
# -fullscreen \

# Theming help
# color window = background, border, separator
# color normal = background, foreground, background-alt, highlight-background, highlight-foreground
# color active = background, foreground, background-alt, highlight-background, highlight-foreground
# color urgent = background, foreground, background-alt, highlight-background, highlight-foreground
#!/bin/bash

# Custom Rofi Script

# Launch Rofi
MENU="$(rofi -no-lazy-grab -sep "|" -dmenu -i -p 'System :' \
-hide-scrollbar true \
-bw 0 \
-lines 4 \
-line-padding 10 \
-padding 20 \
-width 15 \
-xoffset 7 -yoffset 36 \
-location 1 \
-columns 1 \
-show-icons -icon-theme "Papirus" \
-font "Fira Sans 12" \
<<< "  Lock|  Logout|  Reboot|  Shutdown")"
case "$MENU" in
  *Lock) ~/dotfiles/scripts/bspwm/lock ;;
  *Logout) dwm-msg run_command quit ;;
  *Reboot) systemctl reboot ;;
  *Shutdown) systemctl -i poweroff
esac
# vim:ft=bash
