#!/bin/bash
source ~/dotfiles/conf/xorg/xinit-common
dex -a
picom --experimental-backends -b --config ~/dotfiles/conf/picom/common.conf
sxhkd 2> ~/.cache/sxhkd.log &

convert ~/.cache/wal/background.svg ~/.cache/wal/background.png
hsetroot -tile ~/.cache/wal/background.png

## Berry Config:
source ~/.cache/wal/colors.sh

# Set decoration geometry
berryc border_width       0
berryc inner_border_width 4
berryc title_height       22
berryc top_gap            30

# Set decoration colors
berryc focus_color         "$(echo "$color8" | sed -e "s/#//")"
berryc unfocus_color       "$(echo "$color8" | sed -e "s/#//")"
berryc inner_focus_color   "$(echo "$color8" | sed -e "s/#//")"
berryc inner_unfocus_color "$(echo "$color0" | sed -e "s/#//")"
berryc text_focus_color    "$(echo "$color15" | sed -e "s/#//")"
berryc text_unfocus_color  "$(echo "$color8" | sed -e "s/#//")"

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Inter-10"

#vim:ft=sh
